name: Smarter Code Owners
description: An action that adds various features meant to work alongside GitHub's default CODEOWNERS.

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  config-path:
    description: 'Path to the smarter-codeowners-config.json file'
    required: false
    default: './smarter-codeowners-config.json'
  comment-title:
    description: 'Title for the code owners comment'
    required: false
    default: '👥 Code Owners'

runs:
  using: node20
  main: dist/index.js