name: Build & Publish APT Repo

# Trigger the workflow whenever you push new .deb files or change the workflow itself
on:
  push:
    paths:
      - 'repos.json'
      - 'ci.sh'
      - 'apt-swarm-public-key.asc'
      - '.github/workflows/deploy-apt-repo.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Run shell script
        env:
          GPG_KEY_ID: D3D7A56E1A3DE7FF
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: chmod +x ci.sh && ./ci.sh

      - name: Upload for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    name: Deploy repo
    needs: build
    runs-on: ubuntu-latest
    environment:
        name: github-pages
        url: ${{ steps.deploy.outputs.page_url }}
    permissions:
        pages: write
        id-token: write
    steps:
        - name: Deploy
          id: deploy
          uses: actions/deploy-pages@v4
